dist: trusty
sudo: false
language: ruby
cache:
  bundler: true
addons:
  chrome: stable
rvm:
  - 2.4.1
node_js:
  - 'node'
before_install:
  - cd frontend && npm i npm@latest -g && cd ..
  - cd frontend && npm ci && cd ..
script:
  - bundle exec rake test
  - cd frontend && npm run ci && cd ..
